import { DIFF_STYLE_SPLIT, NARROW_VIEWPORT_QUERY } from "./constants.js";

export const narrowViewportQuery = window.matchMedia(NARROW_VIEWPORT_QUERY);

// Single mutable store shared across modules. diffStyle is seeded from storage
// in init() before the diff renders.
export const state = {
  token: new URLSearchParams(window.location.search).get("token") || "",
  comments: [],
  files: [],
  filesByPath: new Map(),
  currentPath: "",
  diffStyle: DIFF_STYLE_SPLIT,
  diffStats: { files: 0, additions: 0, deletions: 0, lines: 0 },
  codeView: null,
  CodeView: null,
  workerManager: undefined,
  tree: null,
  draft: null,
  editingId: "",
  hoveredCommentId: "",
  selectedCommentId: "",
  sidebarTab: "files",
  treeCollapsed: false,
  collapsedFiles: new Set(),
  search: {
    word: false,
    regex: false,
    caseSensitive: false,
    error: "",
    response: null,
    controller: null,
    activeKey: "",
    collapsedFiles: new Set(),
  },
  syncingTree: false,
  renderVersion: 0,
  completed: false,
};

export const els = {
  status: document.querySelector("#status"),
  workspace: document.querySelector(".workspace"),
  sidebar: document.querySelector(".sidebar"),
  sidebarResizer: document.querySelector("#sidebar-resizer"),
  tree: document.querySelector("#tree"),
  filesTab: document.querySelector("#files-tab"),
  commentsTab: document.querySelector("#comments-tab"),
  searchTab: document.querySelector("#search-tab"),
  searchCount: document.querySelector("#search-count"),
  searchPanel: document.querySelector("#search-panel"),
  searchForm: document.querySelector("#search-form"),
  searchInput: document.querySelector("#search-input"),
  searchCase: document.querySelector("#search-case"),
  searchWord: document.querySelector("#search-word"),
  searchRegex: document.querySelector("#search-regex"),
  searchStatus: document.querySelector("#search-status"),
  searchResults: document.querySelector("#search-results"),
  peek: document.querySelector("#peek"),
  peekTitle: document.querySelector("#peek-title"),
  peekSource: document.querySelector("#peek-source"),
  peekClose: document.querySelector("#peek-close"),
  peekMessage: document.querySelector("#peek-message"),
  peekView: document.querySelector("#peek-view"),
  treeBackdrop: document.querySelector("#tree-backdrop"),
  diff: document.querySelector("#diff"),
  diffStats: document.querySelector("#diff-stats"),
  diffStatsSummary: document.querySelector("#diff-stats-summary"),
  commentSummary: document.querySelector("#comment-summary"),
  commentNavigator: document.querySelector("#comment-nav"),
  commentNavigatorSummary: document.querySelector("#comment-nav-summary"),
  searchToggle: document.querySelector("#search-toggle"),
  treeToggle: document.querySelector("#tree-toggle"),
  layoutToggle: document.querySelector("#layout-toggle"),
  collapseToggle: document.querySelector("#collapse-toggle"),
  done: document.querySelector("#done"),
};
