import { DIFF_STYLE_SPLIT, NARROW_VIEWPORT_QUERY } from "./constants.js";

export const narrowViewportQuery = window.matchMedia(NARROW_VIEWPORT_QUERY);

// Single mutable store shared across modules. diffStyle is seeded from storage
// in init() before the diff renders.
export const state = {
  token: new URLSearchParams(window.location.search).get("token") || "",
  comments: [],
  files: [],
  filesByPath: new Map(),
  filesByTreePath: new Map(),
  fileKeyToReviewId: new Map(),
  currentPath: "",
  patchText: "",
  diffStyle: DIFF_STYLE_SPLIT,
  diffStats: { files: 0, additions: 0, deletions: 0, lines: 0 },
  codeView: null,
  tree: null,
  draft: null,
  editingId: "",
  hoveredCommentId: "",
  selectedCommentId: "",
  sidebarTab: "files",
  treeCollapsed: false,
  collapsedFiles: new Set(),
  search: {
    open: false,
    query: "",
    matches: [],
    currentIndex: -1,
    truncated: false,
  },
  syncingTree: false,
  renderVersion: 0,
  completed: false,
};

export const els = {
  status: document.querySelector("#status"),
  workspace: document.querySelector(".workspace"),
  sidebar: document.querySelector(".sidebar"),
  sidebarResizer: document.querySelector("#sidebar-resizer"),
  tree: document.querySelector("#tree"),
  filesTab: document.querySelector("#files-tab"),
  commentsTab: document.querySelector("#comments-tab"),
  treeBackdrop: document.querySelector("#tree-backdrop"),
  diff: document.querySelector("#diff"),
  diffStats: document.querySelector("#diff-stats"),
  diffStatsSummary: document.querySelector("#diff-stats-summary"),
  commentSummary: document.querySelector("#comment-summary"),
  commentNavigator: document.querySelector("#comment-nav"),
  commentNavigatorSummary: document.querySelector("#comment-nav-summary"),
  codeSearch: document.querySelector("#code-search"),
  searchToggle: document.querySelector("#search-toggle"),
  searchInput: document.querySelector("#search-input"),
  searchCount: document.querySelector("#search-count"),
  searchPrev: document.querySelector("#search-prev"),
  searchNext: document.querySelector("#search-next"),
  searchClose: document.querySelector("#search-close"),
  treeToggle: document.querySelector("#tree-toggle"),
  layoutToggle: document.querySelector("#layout-toggle"),
  collapseToggle: document.querySelector("#collapse-toggle"),
  done: document.querySelector("#done"),
};
